/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpdRouteImport } from './routes/opd'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpdIndexRouteImport } from './routes/opd/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OpdOpdCardRouteImport } from './routes/opd/opd-card'

const OpdRoute = OpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdIndexRoute = OpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpdRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OpdOpdCardRoute = OpdOpdCardRouteImport.update({
  id: '/opd-card',
  path: '/opd-card',
  getParentRoute: () => OpdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/opd': typeof OpdRouteWithChildren
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/admin/': typeof AdminIndexRoute
  '/opd/': typeof OpdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/admin': typeof AdminIndexRoute
  '/opd': typeof OpdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/opd': typeof OpdRouteWithChildren
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/admin/': typeof AdminIndexRoute
  '/opd/': typeof OpdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/opd' | '/opd/opd-card' | '/admin/' | '/opd/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opd/opd-card' | '/admin' | '/opd'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/opd'
    | '/opd/opd-card'
    | '/admin/'
    | '/opd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  OpdRoute: typeof OpdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opd': {
      id: '/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof OpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd/': {
      id: '/opd/'
      path: '/'
      fullPath: '/opd/'
      preLoaderRoute: typeof OpdIndexRouteImport
      parentRoute: typeof OpdRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/opd/opd-card': {
      id: '/opd/opd-card'
      path: '/opd-card'
      fullPath: '/opd/opd-card'
      preLoaderRoute: typeof OpdOpdCardRouteImport
      parentRoute: typeof OpdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OpdRouteChildren {
  OpdOpdCardRoute: typeof OpdOpdCardRoute
  OpdIndexRoute: typeof OpdIndexRoute
}

const OpdRouteChildren: OpdRouteChildren = {
  OpdOpdCardRoute: OpdOpdCardRoute,
  OpdIndexRoute: OpdIndexRoute,
}

const OpdRouteWithChildren = OpdRoute._addFileChildren(OpdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  OpdRoute: OpdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
