/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpdRouteImport } from './routes/opd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpdIndexRouteImport } from './routes/opd/index'
import { Route as OpdOpdCardRouteImport } from './routes/opd/opd-card'

const OpdRoute = OpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdIndexRoute = OpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpdRoute,
} as any)
const OpdOpdCardRoute = OpdOpdCardRouteImport.update({
  id: '/opd-card',
  path: '/opd-card',
  getParentRoute: () => OpdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opd': typeof OpdRouteWithChildren
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/opd/': typeof OpdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/opd': typeof OpdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opd': typeof OpdRouteWithChildren
  '/opd/opd-card': typeof OpdOpdCardRoute
  '/opd/': typeof OpdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opd' | '/opd/opd-card' | '/opd/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opd/opd-card' | '/opd'
  id: '__root__' | '/' | '/opd' | '/opd/opd-card' | '/opd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpdRoute: typeof OpdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opd': {
      id: '/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof OpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd/': {
      id: '/opd/'
      path: '/'
      fullPath: '/opd/'
      preLoaderRoute: typeof OpdIndexRouteImport
      parentRoute: typeof OpdRoute
    }
    '/opd/opd-card': {
      id: '/opd/opd-card'
      path: '/opd-card'
      fullPath: '/opd/opd-card'
      preLoaderRoute: typeof OpdOpdCardRouteImport
      parentRoute: typeof OpdRoute
    }
  }
}

interface OpdRouteChildren {
  OpdOpdCardRoute: typeof OpdOpdCardRoute
  OpdIndexRoute: typeof OpdIndexRoute
}

const OpdRouteChildren: OpdRouteChildren = {
  OpdOpdCardRoute: OpdOpdCardRoute,
  OpdIndexRoute: OpdIndexRoute,
}

const OpdRouteWithChildren = OpdRoute._addFileChildren(OpdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpdRoute: OpdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
